"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 15:28:58.336613
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', 'trainer', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('oidc_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('onboarding_done', sa.Boolean(), nullable=False),
    sa.Column('ai_monthly_limit_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_oidc_sub'), 'user', ['oidc_sub'], unique=False)
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_created_at'), 'ai_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_user_id'), 'ai_usage', ['user_id'], unique=False)
    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_token_token_hash'), 'api_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_token_user_id'), 'api_token', ['user_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('body_measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('hips_cm', sa.Float(), nullable=True),
    sa.Column('arm_cm', sa.Float(), nullable=True),
    sa.Column('thigh_cm', sa.Float(), nullable=True),
    sa.Column('neck_cm', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_measurement_client_id'), 'body_measurement', ['client_id'], unique=False)
    op.create_index(op.f('ix_body_measurement_day'), 'body_measurement', ['day'], unique=False)
    op.create_index(op.f('ix_body_measurement_user_id'), 'body_measurement', ['user_id'], unique=False)
    op.create_table('cardio_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('track', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cardio_session_client_id'), 'cardio_session', ['client_id'], unique=False)
    op.create_index(op.f('ix_cardio_session_started_at'), 'cardio_session', ['started_at'], unique=False)
    op.create_index(op.f('ix_cardio_session_user_id'), 'cardio_session', ['user_id'], unique=False)
    op.create_table('chat_conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversation_user_id'), 'chat_conversation', ['user_id'], unique=False)
    op.create_table('coach_hint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_hint_created_at'), 'coach_hint', ['created_at'], unique=False)
    op.create_index(op.f('ix_coach_hint_dedupe_key'), 'coach_hint', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_coach_hint_user_id'), 'coach_hint', ['user_id'], unique=False)
    op.create_table('coach_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_note_user_id'), 'coach_note', ['user_id'], unique=False)
    op.create_table('coach_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Text(), nullable=False),
    sa.Column('experience', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=False),
    sa.Column('dislikes', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('equipment', sa.Text(), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('coach_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', 'period_start')
    )
    op.create_index(op.f('ix_coach_summary_period'), 'coach_summary', ['period'], unique=False)
    op.create_index(op.f('ix_coach_summary_period_start'), 'coach_summary', ['period_start'], unique=False)
    op.create_index(op.f('ix_coach_summary_user_id'), 'coach_summary', ['user_id'], unique=False)
    op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('widgets', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_user_id'), 'dashboard', ['user_id'], unique=False)
    op.create_table('day_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entries', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_template_user_id'), 'day_template', ['user_id'], unique=False)
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('equipment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_muscles', sa.JSON(), nullable=False),
    sa.Column('secondary_muscles', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('progression', sa.JSON(), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=False)
    op.create_index(op.f('ix_exercise_owner_id'), 'exercise', ['owner_id'], unique=False)
    op.create_index(op.f('ix_exercise_slug'), 'exercise', ['slug'], unique=False)
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=False),
    sa.Column('sugar', sa.Float(), nullable=False),
    sa.Column('sat_fat', sa.Float(), nullable=False),
    sa.Column('salt', sa.Float(), nullable=False),
    sa.Column('micros', sa.JSON(), nullable=False),
    sa.Column('serving_g', sa.Float(), nullable=True),
    sa.Column('serving_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_barcode'), 'food', ['barcode'], unique=False)
    op.create_index(op.f('ix_food_name'), 'food', ['name'], unique=False)
    op.create_index(op.f('ix_food_owner_id'), 'food', ['owner_id'], unique=False)
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', 'trainer', name='role'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_token_hash'), 'invite', ['token_hash'], unique=True)
    op.create_table('meal_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('shopping_list', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_user_id'), 'meal_plan', ['user_id'], unique=False)
    op.create_index(op.f('ix_meal_plan_week_start'), 'meal_plan', ['week_start'], unique=False)
    op.create_table('metric_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scale_min', sa.Float(), nullable=True),
    sa.Column('scale_max', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('chart', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_definition_user_id'), 'metric_definition', ['user_id'], unique=False)
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_token_hash'), 'password_reset', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_user_id'), 'password_reset', ['user_id'], unique=False)
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('weeks', sa.Integer(), nullable=False),
    sa.Column('deload_weeks', sa.JSON(), nullable=False),
    sa.Column('deload_factor', sa.Float(), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_owner_id'), 'plan', ['owner_id'], unique=False)
    op.create_table('progress_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_photo_day'), 'progress_photo', ['day'], unique=False)
    op.create_index(op.f('ix_progress_photo_user_id'), 'progress_photo', ['user_id'], unique=False)
    op.create_table('prompt_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_template_name'), 'prompt_template', ['name'], unique=False)
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('p256dh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscription_user_id'), 'push_subscription', ['user_id'], unique=False)
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_owner_id'), 'recipe', ['owner_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.create_table('share_grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', 'user_id')
    )
    op.create_index(op.f('ix_share_grant_resource_id'), 'share_grant', ['resource_id'], unique=False)
    op.create_index(op.f('ix_share_grant_resource_type'), 'share_grant', ['resource_type'], unique=False)
    op.create_index(op.f('ix_share_grant_user_id'), 'share_grant', ['user_id'], unique=False)
    op.create_table('trainer_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainer_comment_athlete_id'), 'trainer_comment', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_trainer_comment_trainer_id'), 'trainer_comment', ['trainer_id'], unique=False)
    op.create_table('trainer_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_id', 'athlete_id')
    )
    op.create_index(op.f('ix_trainer_link_athlete_id'), 'trainer_link', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_trainer_link_trainer_id'), 'trainer_link', ['trainer_id'], unique=False)
    op.create_table('user_ai_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider')
    )
    op.create_index(op.f('ix_user_ai_key_user_id'), 'user_ai_key', ['user_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('activity_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('training_days_per_week', sa.Integer(), nullable=False),
    sa.Column('custom_targets', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('water_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('ml', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_entry_client_id'), 'water_entry', ['client_id'], unique=False)
    op.create_index(op.f('ix_water_entry_day'), 'water_entry', ['day'], unique=False)
    op.create_index(op.f('ix_water_entry_user_id'), 'water_entry', ['user_id'], unique=False)
    op.create_table('webauthn_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.JSON(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_credential_credential_id'), 'webauthn_credential', ['credential_id'], unique=True)
    op.create_index(op.f('ix_webauthn_credential_user_id'), 'webauthn_credential', ['user_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_conversation_id'), 'chat_message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_message_user_id'), 'chat_message', ['user_id'], unique=False)
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('default_grams', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_user_id'), 'favorite', ['user_id'], unique=False)
    op.create_table('meal_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('slot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('servings', sa.Float(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=False),
    sa.Column('sugar', sa.Float(), nullable=False),
    sa.Column('sat_fat', sa.Float(), nullable=False),
    sa.Column('salt', sa.Float(), nullable=False),
    sa.Column('micros', sa.JSON(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_entry_client_id'), 'meal_entry', ['client_id'], unique=False)
    op.create_index(op.f('ix_meal_entry_day'), 'meal_entry', ['day'], unique=False)
    op.create_index(op.f('ix_meal_entry_user_id'), 'meal_entry', ['user_id'], unique=False)
    op.create_table('metric_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_entry_day'), 'metric_entry', ['day'], unique=False)
    op.create_index(op.f('ix_metric_entry_metric_id'), 'metric_entry', ['metric_id'], unique=False)
    op.create_index(op.f('ix_metric_entry_user_id'), 'metric_entry', ['user_id'], unique=False)
    op.create_table('pending_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_action_user_id'), 'pending_action', ['user_id'], unique=False)
    op.create_table('plan_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_day_plan_id'), 'plan_day', ['plan_id'], unique=False)
    op.create_table('recipe_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredient_recipe_id'), 'recipe_ingredient', ['recipe_id'], unique=False)
    op.create_table('plan_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_day_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('rep_min', sa.Integer(), nullable=False),
    sa.Column('rep_max', sa.Integer(), nullable=False),
    sa.Column('target_rpe', sa.Float(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('superset_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_day_id'], ['plan_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_exercise_plan_day_id'), 'plan_exercise', ['plan_day_id'], unique=False)
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('plan_day_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_deload', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_day_id'], ['plan_day.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_client_id'), 'workout', ['client_id'], unique=False)
    op.create_index(op.f('ix_workout_started_at'), 'workout', ['started_at'], unique=False)
    op.create_index(op.f('ix_workout_user_id'), 'workout', ['user_id'], unique=False)
    op.create_table('workout_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('superset_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_set_client_id'), 'workout_set', ['client_id'], unique=False)
    op.create_index(op.f('ix_workout_set_exercise_id'), 'workout_set', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_set_user_id'), 'workout_set', ['user_id'], unique=False)
    op.create_index(op.f('ix_workout_set_workout_id'), 'workout_set', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_set_workout_id'), table_name='workout_set')
    op.drop_index(op.f('ix_workout_set_user_id'), table_name='workout_set')
    op.drop_index(op.f('ix_workout_set_exercise_id'), table_name='workout_set')
    op.drop_index(op.f('ix_workout_set_client_id'), table_name='workout_set')
    op.drop_table('workout_set')
    op.drop_index(op.f('ix_workout_user_id'), table_name='workout')
    op.drop_index(op.f('ix_workout_started_at'), table_name='workout')
    op.drop_index(op.f('ix_workout_client_id'), table_name='workout')
    op.drop_table('workout')
    op.drop_index(op.f('ix_plan_exercise_plan_day_id'), table_name='plan_exercise')
    op.drop_table('plan_exercise')
    op.drop_index(op.f('ix_recipe_ingredient_recipe_id'), table_name='recipe_ingredient')
    op.drop_table('recipe_ingredient')
    op.drop_index(op.f('ix_plan_day_plan_id'), table_name='plan_day')
    op.drop_table('plan_day')
    op.drop_index(op.f('ix_pending_action_user_id'), table_name='pending_action')
    op.drop_table('pending_action')
    op.drop_index(op.f('ix_metric_entry_user_id'), table_name='metric_entry')
    op.drop_index(op.f('ix_metric_entry_metric_id'), table_name='metric_entry')
    op.drop_index(op.f('ix_metric_entry_day'), table_name='metric_entry')
    op.drop_table('metric_entry')
    op.drop_index(op.f('ix_meal_entry_user_id'), table_name='meal_entry')
    op.drop_index(op.f('ix_meal_entry_day'), table_name='meal_entry')
    op.drop_index(op.f('ix_meal_entry_client_id'), table_name='meal_entry')
    op.drop_table('meal_entry')
    op.drop_index(op.f('ix_favorite_user_id'), table_name='favorite')
    op.drop_table('favorite')
    op.drop_index(op.f('ix_chat_message_user_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_conversation_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_webauthn_credential_user_id'), table_name='webauthn_credential')
    op.drop_index(op.f('ix_webauthn_credential_credential_id'), table_name='webauthn_credential')
    op.drop_table('webauthn_credential')
    op.drop_index(op.f('ix_water_entry_user_id'), table_name='water_entry')
    op.drop_index(op.f('ix_water_entry_day'), table_name='water_entry')
    op.drop_index(op.f('ix_water_entry_client_id'), table_name='water_entry')
    op.drop_table('water_entry')
    op.drop_table('user_settings')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_user_ai_key_user_id'), table_name='user_ai_key')
    op.drop_table('user_ai_key')
    op.drop_index(op.f('ix_trainer_link_trainer_id'), table_name='trainer_link')
    op.drop_index(op.f('ix_trainer_link_athlete_id'), table_name='trainer_link')
    op.drop_table('trainer_link')
    op.drop_index(op.f('ix_trainer_comment_trainer_id'), table_name='trainer_comment')
    op.drop_index(op.f('ix_trainer_comment_athlete_id'), table_name='trainer_comment')
    op.drop_table('trainer_comment')
    op.drop_index(op.f('ix_share_grant_user_id'), table_name='share_grant')
    op.drop_index(op.f('ix_share_grant_resource_type'), table_name='share_grant')
    op.drop_index(op.f('ix_share_grant_resource_id'), table_name='share_grant')
    op.drop_table('share_grant')
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_recipe_owner_id'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_push_subscription_user_id'), table_name='push_subscription')
    op.drop_table('push_subscription')
    op.drop_index(op.f('ix_prompt_template_name'), table_name='prompt_template')
    op.drop_table('prompt_template')
    op.drop_index(op.f('ix_progress_photo_user_id'), table_name='progress_photo')
    op.drop_index(op.f('ix_progress_photo_day'), table_name='progress_photo')
    op.drop_table('progress_photo')
    op.drop_index(op.f('ix_plan_owner_id'), table_name='plan')
    op.drop_table('plan')
    op.drop_index(op.f('ix_password_reset_user_id'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_token_hash'), table_name='password_reset')
    op.drop_table('password_reset')
    op.drop_index(op.f('ix_metric_definition_user_id'), table_name='metric_definition')
    op.drop_table('metric_definition')
    op.drop_index(op.f('ix_meal_plan_week_start'), table_name='meal_plan')
    op.drop_index(op.f('ix_meal_plan_user_id'), table_name='meal_plan')
    op.drop_table('meal_plan')
    op.drop_index(op.f('ix_invite_token_hash'), table_name='invite')
    op.drop_table('invite')
    op.drop_index(op.f('ix_food_owner_id'), table_name='food')
    op.drop_index(op.f('ix_food_name'), table_name='food')
    op.drop_index(op.f('ix_food_barcode'), table_name='food')
    op.drop_table('food')
    op.drop_index(op.f('ix_exercise_slug'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_owner_id'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_table('exercise')
    op.drop_index(op.f('ix_day_template_user_id'), table_name='day_template')
    op.drop_table('day_template')
    op.drop_index(op.f('ix_dashboard_user_id'), table_name='dashboard')
    op.drop_table('dashboard')
    op.drop_index(op.f('ix_coach_summary_user_id'), table_name='coach_summary')
    op.drop_index(op.f('ix_coach_summary_period_start'), table_name='coach_summary')
    op.drop_index(op.f('ix_coach_summary_period'), table_name='coach_summary')
    op.drop_table('coach_summary')
    op.drop_table('coach_profile')
    op.drop_index(op.f('ix_coach_note_user_id'), table_name='coach_note')
    op.drop_table('coach_note')
    op.drop_index(op.f('ix_coach_hint_user_id'), table_name='coach_hint')
    op.drop_index(op.f('ix_coach_hint_dedupe_key'), table_name='coach_hint')
    op.drop_index(op.f('ix_coach_hint_created_at'), table_name='coach_hint')
    op.drop_table('coach_hint')
    op.drop_index(op.f('ix_chat_conversation_user_id'), table_name='chat_conversation')
    op.drop_table('chat_conversation')
    op.drop_index(op.f('ix_cardio_session_user_id'), table_name='cardio_session')
    op.drop_index(op.f('ix_cardio_session_started_at'), table_name='cardio_session')
    op.drop_index(op.f('ix_cardio_session_client_id'), table_name='cardio_session')
    op.drop_table('cardio_session')
    op.drop_index(op.f('ix_body_measurement_user_id'), table_name='body_measurement')
    op.drop_index(op.f('ix_body_measurement_day'), table_name='body_measurement')
    op.drop_index(op.f('ix_body_measurement_client_id'), table_name='body_measurement')
    op.drop_table('body_measurement')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_api_token_user_id'), table_name='api_token')
    op.drop_index(op.f('ix_api_token_token_hash'), table_name='api_token')
    op.drop_table('api_token')
    op.drop_index(op.f('ix_ai_usage_user_id'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_created_at'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_user_oidc_sub'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
