"""food external id and category

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 18:11:11.016671
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('food', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.create_index(op.f('ix_food_external_id'), 'food', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_external_id'), table_name='food')
    op.drop_column('food', 'category')
    op.drop_column('food', 'external_id')
    # ### end Alembic commands ###
