"""exercise media id

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-28 18:28:31.778813
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('media_id', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'media_id')
    # ### end Alembic commands ###
